# -*- coding: utf-8 -*-
"""uas_yazidnh_2003040024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lV4cFrjT0QJ3tTG-5XixzAGMkwnykvpg
"""

import warnings
warnings.filterwarnings('ignore')

import geopandas as gpd

pip install geopandas

gdf = gpd.read_file("RBI25K_ADMINISTRASI_LN.json")
gdf.head()

gdf = gdf[['NAMOBJ', 'FCODE', 'REMARK', 'METADATA', 'geometry']].fillna(0)

!pip install folium matplotlib mapclassify

import folium
m = gdf.explore(column="METADATA", name="MetaData")
folium.LayerControl().add_to(m)
m